editor: source

execute:
  cache: false
  freeze: false

project:
  type: website
  output-dir: docs
  post-render: "R/_post-render.R"

title: "SIMBRA"
description: |
  1.º Simpósio Interdisciplinar Brasileiro de Modelos Baseados em Agentes
keyword: >
  Simpósio. Interdisciplinaridade. Modelos Baseados em Agentes.
  Sistemas Complexos Ciência da Complexidade. Simulações.
website:
  favicon: images/favicon.svg
  site-url: https://simbra.com.br/
  repo-url: https://github.com/simbra-org/simbra-org.github.io/
  issue-url: https://github.com/simbra-org/simbra-org.github.io/issues/
  open-graph:
    locale: pt_BR
    image: images/og-image.png
    image-width: 2400
    image-height: 1600
    image-alt: "Simpósio Interdisciplinar Brasileiro de Modelos Baseados em Agentes (SIMBRA)"
  repo-branch: main
  navbar: false
  sidebar: false

format:
  html:
    open-graph: true
    locale: pt_BR
    lang: pt_BR
    code-link: true
    code-fold: true
    tbl-cap-location: top
    callout-appearance: simple
    csl: csl/english-apa-author-date.csl
    fig-align: center
    repo-actions: false
    link-external-newwindow: true
    theme: [default, brand, scss/styles.scss]
    include-in-header:
      text: |
        <meta property="og:description" content="">
        <meta property="og:image" content="https://simbra-org.github.io/images/og-image.png">
        <meta property="og:image:height" content="2400">
        <meta property="og:image:width" content="1600">
